<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="3.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrainWeb.Application\TrainWeb.Application.csproj" />
    <ProjectReference Include="..\TrainWeb.Domain\TrainWeb.Domain.csproj" />
  </ItemGroup>

</Project>
