<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>35713468-8892-4720-b895-6dbfdf745f41</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="firebase-key.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="FirebaseAdmin" Version="3.4.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Google.Cloud.Firestore" Version="3.10.0" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TrainWeb.Application\TrainWeb.Application.csproj" />
    <ProjectReference Include="..\TrainWeb.Infrastructure\TrainWeb.Infrastructure.csproj" />
  </ItemGroup>

</Project>